# Generated by Django 4.2 on 2023-04-06 18:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_amount", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quotation_status",
                    models.TextField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                    ),
                ),
                (
                    "amount_client_recieves",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("expiration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ClientModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.TextField(max_length=64)),
                ("cuit_or_ruc", models.TextField(max_length=15)),
                ("email", models.TextField(max_length=64)),
                ("phone", models.TextField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="ExpensesModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discount_rate", models.FloatField(blank=True, default=0, null=True)),
                (
                    "payment_date_discount",
                    models.FloatField(blank=True, default=0, null=True),
                ),
                ("expenses", models.FloatField(blank=True, default=0, null=True)),
                (
                    "check_realtion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="app.checkmodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="checkmodel",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="checks",
                to="app.clientmodel",
            ),
        ),
    ]
