# Generated by Django 4.2 on 2023-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expensesmodel",
            old_name="discount_rate",
            new_name="total_discounts",
        ),
        migrations.RemoveField(
            model_name="expensesmodel",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="expensesmodel",
            name="payment_date_discount",
        ),
        migrations.AlterField(
            model_name="checkmodel",
            name="amount_client_recieves",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
