# Generated by Django 4.2 on 2023-04-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_discount_rate_expensesmodel_total_discounts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkmodel",
            name="client",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="checks",
                to="app.clientmodel",
            ),
        ),
    ]
