# Generated by Django 4.2 on 2023-04-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_checkmodel_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expensesmodel",
            old_name="check_realtion",
            new_name="check_relation",
        ),
    ]
