# Generated by Django 4.2 on 2023-04-13 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_check_realtion_expensesmodel_check_relation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkmodel",
            name="client",
        ),
        migrations.AddField(
            model_name="checkmodel",
            name="client_check_key",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="client_check",
                to="app.clientmodel",
            ),
        ),
    ]
